In [1]:
!pip install h5py

In [2]:
import h5py
h5f = h5py.File('./SVHN_single_grey1.h5', 'r')

# Load the training and the test set
X_train = h5f['X_train'][:]
y_train = h5f['y_train'][:]
X_test = h5f['X_test'][:]
y_test = h5f['y_test'][:]


# Close this file
h5f.close()

In [3]:
len(X_train), len(X_test),X_train.shape, X_test.shape

(42000, 18000, (42000, 32, 32), (18000, 32, 32))

In [4]:
X_train = X_train.reshape(X_train.shape[0], 1024)
X_test = X_test.reshape(X_test.shape[0], 1024)
# Normalize inputs from 0-255 to 0-1

X_train = X_train/255
X_test = X_test/255

In [5]:
svh_x_train, svh_x_test, svh_y_train, svh_y_test = X_train, X_test, y_train, y_test

In [6]:
from util import Utils

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [7]:
from sklearn.model_selection import train_test_split

svh_X_train, svh_X_val, svh_Y_train, svh_y_val = train_test_split(svh_x_train, svh_y_train, test_size=1/3, random_state=42)

In [8]:
svh_y_train

array([2, 6, 7, ..., 7, 0, 4], dtype=uint8)

In [9]:
best_svh_model = Utils.find_best_rf_parameters(svh_x_train, svh_y_train)

Fitting 3 folds for each of 1 candidates, totalling 3 fits


/home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/sklearn/model_selection/_search.py:307: UserWarning: The total space of parameters 1 is smaller than n_iter=10. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(



All Results:
{'n_estimators': 100, 'max_features': 'log2', 'max_depth': 100, 'criterion': 'entropy'} with accuracy: 0.6871428571428572

--- 226.20513081550598 seconds ---
The highest Accuracy 0.68714 is the model with parameters: {'n_estimators': 100, 'max_features': 'log2', 'max_depth': 100, 'criterion': 'entropy'}


In [10]:
Utils.accuracy_measure_rf(svh_x_train, svh_y_train, 
                          svh_x_test, svh_y_test, 
                          n_estimators = 100, criterion = 'entropy', max_depth = 50, max_features = 'sqrt')

[CV] END criterion=entropy, max_depth=100, max_features=log2, n_estimators=100; total time= 1.5min
[CV] END criterion=entropy, max_depth=100, max_features=log2, n_estimators=100; total time= 1.5min
[CV] END criterion=entropy, max_depth=100, max_features=log2, n_estimators=100; total time= 1.5min
--- 423.7103843688965 seconds ---


(0.7425,
 (array([0.70625303, 0.70976876, 0.79976303, 0.67185762, 0.76      ,
         0.73681055, 0.74186047, 0.81288864, 0.74454429, 0.75650118]),
  array([0.80319735, 0.82275711, 0.74875208, 0.70273415, 0.80739514,
         0.69513575, 0.69650655, 0.79535398, 0.6401766 , 0.70953437]),
  array([0.75161207, 0.7620978 , 0.77341736, 0.6869491 , 0.782981  ,
         0.71536671, 0.71846847, 0.80402572, 0.6884273 , 0.73226545]),
  array([1814, 1828, 1803, 1719, 1812, 1768, 1832, 1808, 1812, 1804])))

In [11]:
best_xgb_model = Utils.find_best_xgb_parameters(svh_X_train, svh_Y_train, svh_X_val, svh_y_val)

Fitting 3 folds for each of 1 candidates, totalling 3 fits


/home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/sklearn/model_selection/_search.py:307: UserWarning: The total space of parameters 1 is smaller than n_iter=10. Running 1 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

The exit codes of the workers are {SIGKILL(-9)}

In [ ]:
print("a")