In [1]:
import torch
import numpy as np

ModuleNotFoundError: No module named 'torch'

In [2]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [3]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [4]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.5524, 0.9418],
        [0.6768, 0.8662]]) 



In [5]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.7980, 0.1123, 0.7460],
        [0.0599, 0.5767, 0.5258]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
tensor = torch.rand(3, 4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [7]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print(f"Device tensor is stored on: {tensor.device}")

In [8]:
import torch
torch.cuda.is_available()


False

In [1]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())


ModuleNotFoundError: No module named 'torch'

In [2]:
print(torch.version.cuda)


12.1


In [ ]:
!pip uninstall torch torchvision torchaudio


Found existing installation: torch 2.1.2
Uninstalling torch-2.1.2:
  Would remove:
    /home/ahmad/anaconda3/envs/rapids-23.12/bin/convert-caffe2-to-onnx
    /home/ahmad/anaconda3/envs/rapids-23.12/bin/convert-onnx-to-caffe2
    /home/ahmad/anaconda3/envs/rapids-23.12/bin/torchrun
    /home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/functorch/*
    /home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/nvfuser/*
    /home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/torch-2.1.2.dist-info/*
    /home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/torch/*
    /home/ahmad/anaconda3/envs/rapids-23.12/lib/python3.10/site-packages/torchgen/*
Proceed (Y/n)? 

In [2]:
!conda install pytorch torchvision torchaudio cudatoolkit=11.8 -c pytorch


Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Solving environment: unsuccessful initial attempt using frozen solve. Retrying with flexible solve.
Solving environment: - ^C
failed

CondaError: KeyboardInterrupt

